--Them cot trang thai phe duyet
ALTER TABLE  MEETING_MEMBER_REPLATE
ADD ("STATUS_APPROVAL" NUMBER(1,0));

-- Them cot id nguoi phe duyet
ALTER TABLE  MEETING_MEMBER_REPLATE
ADD ("APPROVAL_ID" NUMBER(22,0));

-- Them cot thoi gian phe duyet
ALTER TABLE  MEETING_MEMBER_REPLATE
ADD ("TIME_APPROVAL" DATE);

-- Them cot ly do phe duyet
ALTER TABLE  MEETING_MEMBER_REPLATE
ADD ("REASON_APPROVAL" VARCHAR2(4000 BYTE));

-- Them cot  chu tri
ALTER TABLE  MEETING_MEMBER_REPLATE
ADD ("IS_PRESIDENT" NUMBER(22,0));


-- Them cot IS_DIRECTOR
    ALTER TABLE  MEETING_MEMBER
    ADD ("IS_DIRECTOR" NUMBER(1,0));

commit;