--Them cot cho table AVERAGE_TASK_RATING o db2
ALTER TABLE  AVERAGE_TASK_RATING 
ADD (COMPLY_RULE NUMBER(1,0),
	COMPLY_RULE_NOTE  NVARCHAR2(2000),
	COMPLY_LOCATION NUMBER(1,0), 
    COMPLY_LOCATION_NOTE NVARCHAR2(2000),
	PERIOD_TYPE NUMBER(1,0)
 );
commit;