ALTER TABLE MISSION_NORM 
ADD (CREATED_DATE DATE );
ALTER TABLE MISSION_NORM 
ADD (CREATED_BY NUMBER(20) );
ALTER TABLE MISSION_NORM 
ADD (CREATED_ORG NUMBER(20) );
ALTER TABLE MISSION_NORM 
ADD (UPDATED_DATE DATE );
ALTER TABLE MISSION_NORM 
ADD (UPDATED_BY NUMBER(20) );

Insert into SYS_MENU (SYS_MENU_ID,CODE,NAME,PATH,URL,PARENT_ID,SORT_ORDER,IMAGE,DESCRIPTION,GENERATED_SORT_ORDER,STATUS,CREATED_DATE,CREATED_BY,UPDATED_DATE,UPDATED_BY,DELETED_BY,DELETED_DATE,DEL_FLAG,KEY_NAME) values (338953,'MISSION_NORM','Quản lý chỉ tiêu','/337971/338953/','/view/voffice/mission/missionNorm/missionNorm.zul',337971,13,'fa-cubes','Quản lý chỉ tiêu','/005/013/',1,null,null,null,null,null,null,'0','voffice.menu.mission.missionNorm');

CREATE SEQUENCE MISSION_NORM_SEQ START WITH 64;
